---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: document
  path: source/404/index.md
  label: '404'
- type: directory
  path: source/_posts/code
  label: code
  create: documents
  match: "*.md"
  templates:
  - blog-post
- type: directory
  path: source/_posts/hardware
  label: hardware
  create: documents
  match: "*.md"
  templates:
  - blog-post
- type: directory
  path: source/_posts/linux
  label: linux
  create: documents
  match: "*.md"
  templates:
  - blog-post
- type: directory
  path: source/_posts/network
  label: network
  create: documents
  match: "*.md"
  templates:
  - blog-post
- type: directory
  path: source/_drafts
  label: Draft
  create: documents
  match: "*.md"
  templates:
  - blog-post
upload_dir: source/images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run preview
